WIDTH = 950
HEIGHT = 750

TETRIS_TILE_SIZE = 35
TETRIS_ROWS = 20
TETRIS_COLS = 10

MAIN_BOARD_X_OFFSET = (WIDTH - TETRIS_TILE_SIZE * TETRIS_COLS) / 2
MAIN_BOARD_Y_OFFSET = (HEIGHT - TETRIS_TILE_SIZE * TETRIS_ROWS) / 2