WIDTH = 950
HEIGHT = 750

TETRIS_TILE_SIZE = 35
TETRIS_ROWS = 20
TETRIS_COLS = 10

MAIN_BOARD_X_OFFSET = (WIDTH - TETRIS_TILE_SIZE * TETRIS_COLS) / 2
MAIN_BOARD_Y_OFFSET = (HEIGHT - TETRIS_TILE_SIZE * TETRIS_ROWS) / 2


SQUARE_PANEL_SIZE = 5

NEXT_PANEL_X_OFFSET = (TETRIS_TILE_SIZE * TETRIS_COLS) + MAIN_BOARD_X_OFFSET + (MAIN_BOARD_X_OFFSET - TETRIS_TILE_SIZE * SQUARE_PANEL_SIZE) / 2
NEXT_PANEL_Y_OFFSET = (HEIGHT - TETRIS_TILE_SIZE * SQUARE_PANEL_SIZE) / 2

HOLD_PANEL_X_OFFSET = (MAIN_BOARD_X_OFFSET - TETRIS_TILE_SIZE * SQUARE_PANEL_SIZE) / 2
HOLD_PANEL_Y_OFFSET = HEIGHT / 7


PIECE_STARTING_X = 4
PIECE_STARTING_Y = 1

PIECE_SIDE_PANEL_X = 2
PIECE_SIDE_PANEL_Y = 2

# COLORS
MAIN_BACKGROUND_COLOR = "#29303b"
FIELDS_COLOR = "#3e4756"

MEDIUM_BLUE = (60, 130, 200)
PURPLE = (155, 0, 228)
ORANGE = (255, 200, 0)
REGULAR_BLUE = (0, 0, 255)
SKY_BLUE = (30, 220, 252)
YELLOW = (255, 255, 0)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
COOL_WHITE = "#ddf2ff"